services:
  mqtt:
    image: eclipse-mosquitto:latest
    pull_policy: always
    container_name: mqtt
    network_mode: "host"
    volumes:
      - "${CONFIG}:/mosquitto/config"
      - "${DATA}:/mosquitto/data"
      - "${LOG}:/mosquitto/log"
